runtime: java
env: flex

runtime_config:  
  jdk: openjdk17

handlers:
- url: /.*
  script: this field is required, but ignored

manual_scaling:
  instances: 1  

env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"  # Set a Spring profile for GCP-specific configurations
